[defaults]
branchPrefixes = ["feature/", "bugfix/", "tech/"]

[defaults.nightly]
prefix = ""
suffix = ""
defaultBranches = ["master", "main"]

[defaults.properties]
foo = "baz"

[strategy.java]
[strategy.java.nightly]
prefix = "v0.0.0-"
suffix = "-SNAPSHOT"

[strategy.npm]
[strategy.npm.nightly]
prefix = "v0.0.0-"
[strategy.npm.properties]
foo = "bar"

[strategy.docker]
enabled = true
type = "container"
