platform: auto

defaults:
  branchPrefixes:
    - feature/
    - bugfix/
    - tech/

  nightly:
    defaultBranches:
      - main
    prefixTpl: "{{ commitInfo.previousSemVerReleaseVersion | semver_inc: 'minor' | append: '-' }}"
    branchIdentifierTpl: "{% if branchIdentifier %}{{ branchIdentifier | truncate: 20, '' | trim_alphanumeric | append: '.' }}{% endif %}"
    commitIdentifierTpl: "{{ commitInfo.dateTime }}.{{ commitInfo.sha | truncate: 12, '' }}"
    versionTpl: "{{ prefix }}{{ branchIdentifier }}{{ commitIdentifier }}{{ suffix }}"

strategies:
  docker:
    enabled: true
    type: container
    tags:
      enabled: true
      nightly:
        - "{{ version }}"
        - "{{ commitInfo.sha }}"
        - "{% if config.nightly.defaultBranches contains commitInfo.refName %}{{ commitInfo.refName }}{% endif %}"
      tagged:
        - "{{ version }}"
      semVer:
        - "{{ version }}"
        - "{% if versionInfo.isHighestSameMinorVersion %}{{ semVer.major }}.{{ semVer.minor }}{% endif %}"
        - "{% if versionInfo.isHighestSameMajorVersion and semVer.major > 0 %}{{ semVer.major }}{% endif %}"
        - "{% if versionInfo.isHighestSemVerReleaseVersion %}latest{% endif %}"

  npm:
    enabled: false

  java:
    enabled: false
    nightly:
      suffixTpl: "-SNAPSHOT"

output:
  prefix: GTS_
