# docker containers
[strategy.docker]
type = "container"
enabled = true
[strategy.docker.tags]
enabled = true
nightly = [
    "{{ version }}",
    "{{ commitInfo.sha }}",
    "{% if config.nightly.defaultBranches contains commitInfo.refName %}{{ commitInfo.refName }}{% endif %}",
]
tagged = ["{{ version }}"]
semVer = [
    "{{ version }}",
    "{% if versionInfo.isHighestSameMinorVersion %}{{ semVer.major }}.{{ semVer.minor }}{% endif %}",
    "{% if versionInfo.isHighestSameMajorVersion and semVer.major > 0 %}{{ semVer.major }}{% endif %}",
    "{% if versionInfo.isHighestSemVerReleaseVersion %}latest{% endif %}",
]

# NPM
[strategy.npm]
enabled = false

# Java
[strategy.java]
enabled = true
[strategy.java.nightly]
suffixTpl = "-SNAPSHOT"
