name: "git-that-semver"
description: "Generates build version numbers and metadata based on your git repository state"
outputs:
  GTS_JSON:
    description: "git-that-semver result in JSON format"
runs:
  using: "docker"
  image: "../../../Dockerfile"
  entrypoint: "/entrypoint-action.sh"
